backend:
  name: git-gateway
  branch: master 
  site_url: http://paralelodelivery.netlify.com
publish_mode: editorial_workflow
media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: src/content/blogContent
    create: true
    identifier_field: blog
    fields:
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: featuredimage, label: Featured Image, widget: image }
      - { name: body, label: Body, widget: markdown }